section .text
    global _start

_start:
    mov rbx, 0x0
    mov rcx, 0x1000
    mov rdx, 0x6
    mov rsi, 0x10
    mov rdi, -1
    mov rbp, 0x0
    mov rax, 0x4 ; set up mmap call that allocates one page

    int 0x80

    mov byte [rax], 0x42 ; write to the address generated by the mmap call, should page fault

    mov bl, byte [rax] ; read from the address we wrote to
    cmp bl, 0x42 ; if reading gives us what we expect, exit with code 0
    je _success

    mov rbx, -1 ; else, exit with code -1, panicking the kernel
    mov rax, 0x1
    int 0x80

_success: 
    mov rbx, 0x0
    mov rax, 0x1
    int 0x80
